name: imm-自动更新检测

on:
  workflow_dispatch:
  schedule:
    - cron: "0 18 * * *"

env:
  TZ: Asia/Shanghai

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: 获取 25.12 提交哈希
        id: hash_25
        run: |
          git clone --depth 1 https://github.com/immortalwrt/immortalwrt.git -b openwrt-25.12 imm25
          echo "hash=$(git -C imm25 rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: 缓存 25.12 哈希
        id: cache_25
        uses: actions/cache@v4
        with:
          path: .hash_25
          key: imm25_${{ steps.hash_25.outputs.hash }}

      - name: 触发 25.12 编译
        if: steps.cache_25.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@main
        with:
          token: ${{ github.token }}
          event-type: imm-r2s-25.12

      - name: 获取 23.05 提交哈希
        id: hash_23
        run: |
          git clone --depth 1 https://github.com/immortalwrt/immortalwrt.git -b openwrt-23.05 imm23
          echo "hash=$(git -C imm23 rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: 缓存 23.05 哈希
        id: cache_23
        uses: actions/cache@v4
        with:
          path: .hash_23
          key: imm23_${{ steps.hash_23.outputs.hash }}

      - name: 触发 23.05 编译
        if: steps.cache_23.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@main
        with:
          token: ${{ github.token }}
          event-type: imm-r2s-23.05

      - name: 删除工作流程运行
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          retain_days: 5
          keep_minimum_runs: 5
